name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: macos-14, platform: OS }
          - { os: macos-14, platform: SIMULATOR }
          - { os: macos-13, platform: SIMULATOR }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build
        env:
          IOS_PLATFORM: ${{ matrix.platform }}
        run: |
          python scripts/boost.py
          python scripts/fmt.py
          python scripts/glog.py
          python scripts/json-c.py
          python scripts/leveldb.py
          python scripts/libintl.py
          python scripts/libuv.py
          python scripts/marisa.py
          python scripts/opencc.py
          python scripts/yaml-cpp.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}-${{ matrix.platform }}
          path: |
            build/*.tar.bz2

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  release:
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Nightly Build"
          files: |
            *.tar.bz2
